[package]
name = "pilocows-backend"
version = "0.6.0"
edition = "2021"

[[bin]]
name = "pilocows-backend"
path = "src/main.rs"

[dependencies]
axum          = { version = "0.7", features = ["macros", "multipart"] }
tokio         = { version = "1",   features = ["full"] }
serde         = { version = "1",   features = ["derive"] }
serde_json    = "1"
sqlx          = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "migrate"] }
tower-http    = { version = "0.5", features = ["cors", "trace"] }
thiserror     = "1"
tracing       = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy       = "0.15"
anyhow        = "1"
chrono        = { version = "0.4", features = ["clock"] }
